---
abstract: 'sends test results to cpan-testers@perl.org'
author:
  - 'David A. Golden <dagolden@cpan.org>'
build_requires:
  Data::Dumper: 0
  File::Find: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Reporter
name: Test-Reporter
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Cwd: 0
  File::Temp: 0
  FileHandle: 0
  Net::SMTP: 0
  Sys::Hostname: 0
  Time::Local: 0
  base: 0
  constant: 0
  perl: 5.005
resources:
  bugtracker: http://code.google.com/p/test-reporter/issues/list
  homepage: http://code.google.com/p/test-reporter/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dagolden/test-reporter.git
version: 1.53_01
