--- #YAML:1.0
name:                Test-Reporter
version:             1.36
abstract:            sends test results to cpan-testers@perl.org
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Spec:                    0
    File::Temp:                    0
    Net::SMTP:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Adam J. Foxson <afoxson@pobox.com>
