---
abstract: 'sends test results to cpan-testers@perl.org'
author:
  - 'Adam J. Foxson <afoxson@pobox.com>'
  - 'David Golden <dagolden@cpan.org>'
  - "Kirrily \"Skud\" Robert <skud@cpan.org>"
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Richard Soderberg <rsod@cpan.org>'
  - 'Kurt Starsinic <Kurt.Starsinic@isinet.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Reporter
provides:
  Test::Reporter:
    file: lib/Test/Reporter.pm
    version: 1.56
  Test::Reporter::Transport:
    file: lib/Test/Reporter/Transport.pm
    version: 1.56
  Test::Reporter::Transport::File:
    file: lib/Test/Reporter/Transport/File.pm
    version: 1.56
  Test::Reporter::Transport::HTTPGateway:
    file: lib/Test/Reporter/Transport/HTTPGateway.pm
    version: 1.56
  Test::Reporter::Transport::Mail::Send:
    file: lib/Test/Reporter/Transport/Mail/Send.pm
    version: 1.56
  Test::Reporter::Transport::Net::SMTP:
    file: lib/Test/Reporter/Transport/Net/SMTP.pm
    version: 1.56
  Test::Reporter::Transport::Net::SMTP::TLS:
    file: lib/Test/Reporter/Transport/Net/SMTP/TLS.pm
    version: 1.56
requires:
  Carp: 0
  Cwd: 0
  Data::Dumper: 0
  File::Find: 0
  File::Temp: 0
  FileHandle: 0
  Net::SMTP: 0
  Sys::Hostname: 0
  Test::More: 0.88
  Time::Local: 0
  base: 0
  constant: 0
resources:
  repository: http://github.com/dagolden/test-reporter
version: 1.56
