---
abstract: 'sends test results to cpan-testers@perl.org'
author:
  - 'Adam J. Foxson <afoxson@pobox.com>'
  - 'David Golden <dagolden@cpan.org>'
  - "Kirrily \"Skud\" Robert <skud@cpan.org>"
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Richard Soderberg <rsod@cpan.org>'
  - 'Kurt Starsinic <Kurt.Starsinic@isinet.com>'
build_requires:
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  List::Util: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Reporter
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Test::Reporter:
    file: lib/Test/Reporter.pm
    version: 1.59
  Test::Reporter::Transport:
    file: lib/Test/Reporter/Transport.pm
    version: 1.59
  Test::Reporter::Transport::File:
    file: lib/Test/Reporter/Transport/File.pm
    version: 1.59
  Test::Reporter::Transport::Null:
    file: lib/Test/Reporter/Transport/Null.pm
    version: 1.59
requires:
  Carp: 0
  Cwd: 0
  File::Temp: 0
  FileHandle: 0
  Sys::Hostname: 0
  Time::Local: 0
  base: 0
  constant: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Test-Reporter
  homepage: https://metacpan.org/release/Test-Reporter
  repository: git://github.com/dagolden/test-reporter.git
version: 1.59
x_contributors:
  - 'Vincent Pit <perl@profvince.com>'
