--- #YAML:1.0
name:                Test-Reporter
version:             1.52
abstract:            sends test results to cpan-testers@perl.org
license:             perl
author:              
    - David Golden <dagolden@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Spec:                    0
    File::Temp:                    0
    Net::SMTP:                     0
    Test:                          0
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
    homepage: http://code.google.com/p/test-reporter/
    bugtracker: http://code.google.com/p/test-reporter/issues/list
    Repository: http://echo.dagolden.com/git/?p=Test-Reporter
    MailingList: http://groups.google.com/group/test-reporter
