--- #YAML:1.0
name:               Test-Reporter
version:            1.5202
abstract:           sends test results to cpan-testers@perl.org
author:
    - David Golden <dagolden@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:  0
    File::Temp:  0
    Net::SMTP:   0
    Test::More:  0.47
resources:
    bugtracker:   http://code.google.com/p/test-reporter/issues/list
    homepage:     http://code.google.com/p/test-reporter/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/test-reporter
    Repository:   http://echo.dagolden.com/git/?p=Test-Reporter
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
