#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Reporter
version:      1.24
version_from: lib/Test/Reporter.pm
installdirs:  site
requires:
    Net::SMTP:                     0
    File::Spec:                    0
    File::Temp:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
